name: "Vite Continuous Deployment"

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: "Install Node"
        uses: actions/setup-node@master
        with:
          node-version: "16.x"

      - name: "Setup git Config"
        run: |
          git config user.name "GitHub Actions Bot"
          git config user.email "<>"

      - name: "Install Dependencies"
        run: npm ci

      - name: "Deploy Build"
        run: |
          npm run build

      - name: "Deploy Build 2"
        run: git add .

      - name: "Deploy Build 3"
        run: git commit -m 'deploy'

      - name: "Deploy Build 5"
        run: git push origin `git subtree split --prefix dist main`:gh-pages --force
